
services:
  postgres:
    image: postgres:15
    container_name: postgres-cadastro
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: cadastro
    ports:
      - "5432:5432"
    volumes:
      - postgres_cadastro_data:/var/lib/postgresql/data
volumes:
  postgres_cadastro_data:
    driver: local
